const councils = [
  "Andhra Pradesh Council",
  "Arunachal Pradesh Council",
  "Assam Council",
  "Bihar Council",
  "Chandigarh Council",
  "Chhattisgarh Council",
  "Dadra and Nagar Haveli Council",
  "Daman and Diu Council",
  "Delhi Council",
  "Goa Council",
  "Gujarat Council",
  "Haryana Council",
  "Himachal Pradesh Council",
  "Jammu and Kashmir Council",
  "Jharkhand Council",
  "Karnataka Council",
  "Kerala Council",
  "Ladakh Council",
  "Lakshadweep Council",
  "Madhya Pradesh Council",
  "Maharashtra Council",
  "Manipur Council",
  "Meghalaya Council",
  "Mizoram Council",
  "Nagaland Council",
  "Odisha Council",
  "Puducherry Council",
  "Punjab Council",
  "Rajasthan Council",
  "Sikkim Council",
  "Tamil Nadu Council",
  "Telangana Council",
  "Tripura Council",
  "Uttar Pradesh Council",
  "Uttarakhand Council",
  "West Bengal Council",
];

const states = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

const specialization = [
  "Ayurveda",
  "General Physician",
  "Dentist",
  "Cardiology",
  "Dermatology",
  "Neurology",
  "Gastroenterology",
  "Oncology",
  "Obstetrics and Gynecology",
  "Orthopedics",
  "Psychiatry",
];

module.exports = { councils, states, specialization };
